apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-cam-gateway
  namespace: default
data:
  intelbras-cam-corr-1: |-
    {
    "broker_uri": "amqp://rabbitmq.default",
    "camera": {
        "id": "7",
        "ip": "172.17.31.2",
        "rtsp_port": "554",
        "http_port":80,
        "user": "projeto",
        "password": "AlunosIfes",
        "stream_channel": 0,
        "channel": 1,
        "zipkin_url":"10.10.2.30",
        "zipkin_port":30200
      }
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intelbras-camera-7
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intelbras-camera-7
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-processing-node-2
      hostNetwork: true
      dnsPolicy: "ClusterFirstWithHostNet"
      containers:
        - name: camera-7
          image: labvisio/intelbras-camera-gateway:v1.0
          command: ["python"]
          args: ["service.py", "../etc/conf/options.json"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: options
              mountPath: /opt/intelbras/etc/conf/
      volumes:
        - name: options
          configMap:
            name: configmap-cam-gateway
            items:
              - key: intelbras-cam-corr-1
                path: options.json

