# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from is_msgs import camera_pb2 as is__msgs_dot_camera__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\roptions.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14is_msgs/camera.proto\"y\n\x15WeaponDetectorOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x19\n\x05model\x18\x03 \x01(\x0b\x32\n.YoloModel\x12\x1d\n\x07\x63\x61meras\x18\x04 \x03(\x0b\x32\x0c.CameraSetup\"\xff\x01\n\tYoloModel\x12\x1e\n\x16people_detection_model\x18\x01 \x01(\t\x12\x19\n\x11weapon_model_file\x18\x02 \x01(\t\x12\x17\n\x0fpeople_nms_conf\x18\x03 \x01(\x02\x12\x17\n\x0fweapon_nms_conf\x18\x04 \x01(\x02\x12\x1d\n\x15people_infer_img_size\x18\x05 \x01(\r\x12\x1d\n\x15weapon_infer_img_size\x18\x06 \x01(\r\x12\x1a\n\x12weapon_class_names\x18\x07 \x03(\t\x12\x0b\n\x03gpu\x18\x08 \x01(\r\x12\x1e\n\x16increase_image_percent\x18\t \x01(\r\"B\n\x0b\x43\x61meraSetup\x12\n\n\x02id\x18\x01 \x01(\x03\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.is.vision.CameraConfigb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,is__msgs_dot_camera__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEAPONDETECTOROPTIONS = _descriptor.Descriptor(
  name='WeaponDetectorOptions',
  full_name='WeaponDetectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='WeaponDetectorOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='WeaponDetectorOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='WeaponDetectorOptions.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cameras', full_name='WeaponDetectorOptions.cameras', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=190,
)


_YOLOMODEL = _descriptor.Descriptor(
  name='YoloModel',
  full_name='YoloModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people_detection_model', full_name='YoloModel.people_detection_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weapon_model_file', full_name='YoloModel.weapon_model_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='people_nms_conf', full_name='YoloModel.people_nms_conf', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weapon_nms_conf', full_name='YoloModel.weapon_nms_conf', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='people_infer_img_size', full_name='YoloModel.people_infer_img_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weapon_infer_img_size', full_name='YoloModel.weapon_infer_img_size', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weapon_class_names', full_name='YoloModel.weapon_class_names', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='YoloModel.gpu', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase_image_percent', full_name='YoloModel.increase_image_percent', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=448,
)


_CAMERASETUP = _descriptor.Descriptor(
  name='CameraSetup',
  full_name='CameraSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CameraSetup.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config', full_name='CameraSetup.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=516,
)

_WEAPONDETECTOROPTIONS.fields_by_name['model'].message_type = _YOLOMODEL
_WEAPONDETECTOROPTIONS.fields_by_name['cameras'].message_type = _CAMERASETUP
_CAMERASETUP.fields_by_name['config'].message_type = is__msgs_dot_camera__pb2._CAMERACONFIG
DESCRIPTOR.message_types_by_name['WeaponDetectorOptions'] = _WEAPONDETECTOROPTIONS
DESCRIPTOR.message_types_by_name['YoloModel'] = _YOLOMODEL
DESCRIPTOR.message_types_by_name['CameraSetup'] = _CAMERASETUP

WeaponDetectorOptions = _reflection.GeneratedProtocolMessageType('WeaponDetectorOptions', (_message.Message,), dict(
  DESCRIPTOR = _WEAPONDETECTOROPTIONS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:WeaponDetectorOptions)
  ))
_sym_db.RegisterMessage(WeaponDetectorOptions)

YoloModel = _reflection.GeneratedProtocolMessageType('YoloModel', (_message.Message,), dict(
  DESCRIPTOR = _YOLOMODEL,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:YoloModel)
  ))
_sym_db.RegisterMessage(YoloModel)

CameraSetup = _reflection.GeneratedProtocolMessageType('CameraSetup', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASETUP,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:CameraSetup)
  ))
_sym_db.RegisterMessage(CameraSetup)


# @@protoc_insertion_point(module_scope)
