---
apiVersion: v1
kind: ConfigMap
metadata:
  name: is-weapons-detector
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default", 
      "zipkin_uri": "http://zipkin.default:9411",
      "model": {
          "people_detection_model": "yolov5m6",
          "weapon_model_file": "/models/yolov5m6-1280.pt",
          "people_nms_conf": 0.4,
          "weapon_nms_conf":0.4,
          "people_infer_img_size":1280,
          "weapon_infer_img_size":1280,
          "increase_image_percent":40,
          "weapon_class_names": ["Arma", "Pessoa Armada"],
          "gpu":0
      }
    }

---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: is-weapons-detector
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "is-weapons-detector"
    spec:
      containers:
      - name: is-weapons-detector
        image: labvisio/is-weapons-detector:0.0.1
        command: ["is-weapons-detector"]
        args: ["/conf/options.json"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: 4096Mi
            nvidia.com/gpu: 1
        volumeMounts:
          - name: options
            mountPath: /conf/
          - name: models
            mountPath: /models
            readOnly: true
      volumes:
      - name: options
        configMap:
          name: is-weapons-detector
          items:
          - key: detector
            path: options.json
      - name: models
        hostPath:
          path: /public/videomonitoramento-ifes/models/weapons-detection/
          type: Directory